### DISCUSSION TITLE
Port forwarding woes on Synology NAS

### DISCUSSION THREAD

**Discussion by joebell1329** [thijsvanloef/palworld-server-docker#541] [Q&A]
Trying to test this out on a Synology NAS, but I'm having some issues with connectivity from outside my network.

I'm using docker-compose with the following config

```
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         PUID: <***>
         PGID: <***>
         PORT: 8211
         PLAYERS: 16
         SERVER_PASSWORD: "<***>"
         MULTITHREADING: true
         RCON_ENABLED: true
         RCON_PORT: 25575
         TZ: "UTC"
         ADMIN_PASSWORD: "<***>"
         COMMUNITY: false
         SERVER_NAME: "<***>"
         SERVER_DESCRIPTION: "<***>"
      volumes:
         - ./data:/palworld/
```

I've set up a DDNS domain using synology DDNS and have forwarded UDP on ports 8211 and 27015 from my router to the NAS.
Firewall is currently disabled on the NAS.

I can only seem to connect to the server in palworld using `<LAN IP>:8211`, but `<Synology ddns domain>:8211` gives me a timeout.

I've tested that port forwarding is working to containers on the NAS by setting up an httpd container just serving an html page and forwarded that port which works fine so I'm not sure what I've done wrong here. Am I missing some additional ports to forward?
