### DISCUSSION TITLE
Is there a problem editing the "PalWorldSettings.ini" file?

### DISCUSSION THREAD

**Discussion by hFerbic** [thijsvanloef/palworld-server-docker#597] [Q&A] [answered]
There are several times to edit the file with my settings, following the guidance to keep the server off. However, every time I turn it on, the settings go back to default. Is there a solution?

**Comment by thijsvanloef** [comment, marked as answer]
By default, the settings will be generated with the environment variables, if you want to change the settings.ini manually, you would need to set: DISABLE_GENERATE_SETTINGS: TRUE
```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
        # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
      environment:
         PUID: 1000
         PGID: 1000
         PORT: 8211 # Optional but recommended
         PLAYERS: 16 # Optional but recommended
         SERVER_PASSWORD: "worldofpals" # Optional but recommended
         MULTITHREADING: true
         RCON_ENABLED: true
         RCON_PORT: 25575
         TZ: "UTC"
         ADMIN_PASSWORD: "adminPasswordHere"
         COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         SERVER_NAME: "palworld-server-docker by Thijs van Loef"
         SERVER_DESCRIPTION: "palworld-server-docker by Thijs van Loef"
         ALLOW_CONNECT_PLATFORM: "Steam"
         DISABLE_GENERATE_SETTINGS: TRUE
      volumes:
         - ./palworld:/palworld/
```
