### ISSUE TITLE
How to upgrade the version of the server

### ISSUE THREAD

**Issue by qika-dev** [thijsvanloef/palworld-server-docker#104]
## To Reproduce

Newest version is v0.1.3.0 but my server is out dated.

Do you know how to upgrade the version of my server? Thanks in advance.

## Desktop (please complete the following information)

- OS: [e.g. Windows 10, Ubuntu, Debian]

## docker-compose.yml contents

```yaml
```

**Comment by 1638234804** [comment]
You can try it. I have re-pulled the docker image and can now enter the game.

**Comment by LuCatIsFun** [comment]
just run `docker restart <you container name>`, enter the game.

**Comment by RoryKirsi** [comment]
> just run `docker restart <you container name>`, enter the game.

doesn't work for me

**Comment by thijsvanloef** [comment]
Assuming you have mounted your palworld data to your host machine (so it does not get deleted if the container is removed), run the following:

- `docker compose down --rmi all`
- `docker compose up -d`

**Comment by RoryKirsi** [comment]
> Assuming you have mounted your palworld data to your host machine (so it does not get deleted if the container is removed), run the following:
> 
> * `docker compose down --rmi all`
> * `docker compose up -d`

sorry I think it my problem, since I moved my all save data before, so I have to lock the appid file, it cause the update fail

**Comment by entropiccode** [comment]
Having issues with this as well. Using docker compose, the `docker-compose down --rmi all` and `docker-compose up -d` commands do not cause the server to update properly. `docker restart <container name>` also fails.

**Comment by fryfrog** [comment]
Can you show your `docker run` or compose file? Do you maybe have updates disabled?

**Comment by entropiccode** [comment]
```
# cat docker-compose.yml
version: '3'

services:
   palworld:
      container_name: palworld_server
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PORT=8211
         - PLAYERS=8
         - MULTITHREADING=true
         - UPDATE_ON_BOOT=true
         - SERVER_NAME="envyUK Palworld Home"
      volumes:
         - ./server-data/:/palworld/ 
```
