### ISSUE TITLE
Can't load updates

### ISSUE THREAD

**Issue by TombSte** [thijsvanloef/palworld-server-docker#117]
## Describe the bug
When the server starts, it is unable to download updates from steam. Now It can't upgrade to the newest versions.

## To Reproduce
Start the server.

## Expected behavior

The updates are downloaded.
## Screenshots

- OS: Windows with docker desktop

## docker-compose.yml contents

```yaml

version: "3"
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=8
         - MULTITHREADING=true
         - UPDATE_ON_BOOT=true
         - MULTITHREADING=false
         - RCON_ENABLED=false
         - COMMUNITY=false
         - SERVER_NAME="xxx"
         - ADMIN_PASSWORD="xxx"
      deploy:
        resources:
          limits:
            cpus: '4.000'
            memory: 13000M
          reservations:
            cpus: '3.000'
            memory: 10000M
      volumes:
         - ./palworld:/palworld/

```

## Container/Host Logs

2024-01-26 00:52:16 [  0%] Checking for available updates...
2024-01-26 00:52:16 [----] Verifying installation...
2024-01-26 00:52:16 [  0%] Downloading update...
2024-01-26 00:52:16 [  0%] Checking for available updates...
2024-01-26 00:52:16 [----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
2024-01-26 00:52:16 src/tier0/threadtools.cpp (3706) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x58b41ad0/0x0xf7688b'
