### ISSUE TITLE
Connect to server time out when reconnecting to server

### ISSUE THREAD

**Issue by chunibyo-wly** [thijsvanloef/palworld-server-docker#134]
Hello, thanks for your excellent work.

Can you give me some advice on why I can not reconnect to the server after return to tile?
But if I restart the container, I can connect to it again.
Is that possible help me on this?

```
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=Asia/Shanghai
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      volumes:
         - /media/share/chunibyo/palworld/:/palworld/
```
