### ISSUE TITLE
Modifying server settings doesn't work

### ISSUE THREAD

**Issue by jexterliangsufe** [thijsvanloef/palworld-server-docker#161]
## Describe the bug

I modify `PalWorldSettings.ini` and then use `docker compose restart` to reboot. But the `PalWorldSettings.ini` doesn't change after rebooting. 

## Desktop (please complete the following information)

- OS: Ubuntu
- Version 22

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp # Required if you want your server to show up in the community servers tab 
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_PASSWORD="123" # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="123456"
         - COMMUNITY=true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME="111"
      volumes:
         - /root/Palworld:/palworld/
```
