### ISSUE TITLE
docker exec -it palworld-server rcon-cli not working

### ISSUE THREAD

**Issue by strangeweek** [thijsvanloef/palworld-server-docker#196]
## Describe the bug\
it said,

`Failed to connect to RCON serverdial tcp 127.0.0.1:25575: connect: connection refused`

I also opened port 25575 and saw no change in results.

## docker-compose.yml contents

```
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
        - 127.0.0.1:25575:25575/tcp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - MULTITHREADING=true
         - UPDATE_ON_BOOT=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
         #- SERVER_PASSWORD=test
         - SERVER_NAME=test
         - ADMIN_PASSWORD=test
      volumes:
         - ./palworld:/palworld/
```
