### ISSUE TITLE
0.18 doesn't properly set the server name

### ISSUE THREAD

**Issue by urbenlegend** [thijsvanloef/palworld-server-docker#197]
## Describe the bug

With the 0.18 update, it seems like the server name is no longer set correctly. For example, my server name is `Frag End,` but in the game's server browser, it now shows up as `"Frag`. This only started happening with today's update.

## To Reproduce

1. Update to 0.18
2. Set the server name to something with multiple words
3. Go into the in-game server list and browse by Recent.
4. Notice that the server name begins with opening double quotes and is truncated.

## Expected behavior

Server name is properly set

## Desktop (please complete the following information)

- OS: [e.g. Windows 10, Ubuntu, Debian]: Arch Linux

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: always
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="redacted"
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
         - SERVER_PASSWORD="redacted"
         - SERVER_NAME="Frag End"
      volumes:
         - ./palworld:/palworld/
```
