### ISSUE TITLE
Lost character when the server restart

### ISSUE THREAD

**Issue by EdenZ** [thijsvanloef/palworld-server-docker#205]
Hi, Just want to know if anyone facing the same issue or not.

Every time I reboot the container, my player has to create a new character and lost all progress. I can see I created a lot character with the save fix tool.

Any idea on this? Thanks.

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/8579358/8fc71c75-217e-4a07-85d6-32434a694b79)

**Comment by thijsvanloef** [comment]
Please share your docker-compose.yml or run command, so I can check if there are config issues

**Comment by rodrigodealexandre** [comment]
We are having the same issue here.
```
root@palgordinhoserver:~# more docker-compose.yml 
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211
         - PLAYERS=16 # Número de vagas do servidor
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="Einstein"
         - COMMUNITY=true  # Mostra o seu servidor na listagem da comunidade.
         - SERVER_PASSWORD="xxxx"
         - SERVER_NAME="palgordinho"
      volumes:
         - ./servidor:/palworld/
root@palgordinhoserver:~# 
```

**Comment by EdenZ** [comment]
I just copied from the readme and add some more env.

```
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - TZ=CN
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="xxx"
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
         - SERVER_PASSWORD="xxx"
         - SERVER_NAME="japari work work"
         - UPDATE_ON_BOOT=false
      volumes:
         - ./palworld:/palworld/
```
