### ISSUE TITLE
SERVER_NAME,SERVER_PASSWORD,ADMIN_PASSWORD is not working in 0.19.0

### ISSUE THREAD

**Issue by okashi-ya** [thijsvanloef/palworld-server-docker#208]
When update to 0.19.0,some enviromnent variables is not working anymore.

This is the log:
```

Success! App '2394010' fully installed.
*****CHECKING FOR EXISTING CONFIG*****
SERVER_NAME="Tres"
SERVER_DESCRIPTION="Tres"
SERVER_PASSWORD="xovgur123"
ADMIN_PASSWORD="xovgur123"
PLAYERS=32
RCON_ENABLED=true
RCON_PORT=25575
BACKUP_ENABLED=true
*****STARTING SERVER*****
**./PalServer.sh -port=8211 -queryport=27015 EpicApp=PalServer**

```
There will be no password when enter the server, and the world name is set to "Default Palworld Server"
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/49012015/96e76160-9bfa-4c7c-93a8-1183a82e9c96)

SERVER_NAME,SERVER_PASSWORD,ADMIN_PASSWORD is not in the command of ./PalServer.sh XXX

in 0.18.0 it looks like:
./PalServer.sh -port=8211 -servername="XXX" -adminpassword="XXX" -queryport=27015

**Comment by thijsvanloef** [comment]
could you please share your docker-compose.yml?

**Comment by okashi-ya** [comment]
docker-compose.yaml is not change

> could you please share your docker-compose.yml?

docker-compose.yml:
```

services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: PalWorldServer
      ports:
        - 48211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=32 # Optional but recommended
         - MULTITHREADING=false
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="adminpassword"
         - COMMUNITY=true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
         - SERVER_PASSWORD="myserverpassword"
         - SERVER_NAME="My PalWorld"
         - SERVER_DESCRIPTION="My Only PalWorld"
         - TZ=UTC
      volumes:
         - /home/PalWorldServer/data/:/palworld/

```
