### ISSUE TITLE
Rcon config file seems to have vanished in latest container build

### ISSUE THREAD

**Issue by q23407u892f** [thijsvanloef/palworld-server-docker#211]
## Describe the bug

executing rcon-cli errors out

```
root@palworld-998b5c4d7-z4mq8:/home/steam/steamcmd# rcon-cli
cli: config: parse file: read file: open rcon.yaml: no such file or directory
```

## To Reproduce

1. exec into pod/container
2. run `rcon-cli` or `backup`
3. get presented with error

## Expected behavior

either an rcon shell should spawn or the appropriate rcon command will be executed

## Screenshots

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/87550097/9cd8c893-996d-48f9-884c-7ce356544dcf)

## Desktop (please complete the following information)

- OS: Ubuntu 20.04
## docker-compose.yml contents

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palworld
  namespace: palworld
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: palworld
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: palworld
  template:
    metadata:
      labels:
        app: palworld
        name: palworld
    spec:
      containers:
      - name: palworld
        image: thijsvanloef/palworld-server-docker:latest
        env:
        - name: PLAYERS
          value: "16"

```
