### ISSUE TITLE
Most recent PR merge is ignoring env vars

### ISSUE THREAD

**Issue by lrobles-iterable** [thijsvanloef/palworld-server-docker#212]
## Describe the bug

After the most recent PR merge https://github.com/thijsvanloef/palworld-server-docker/pull/203/, settings in Palworldsettings.ini are being ignored.

Things such as server name, server password are not being set after removing them from the startup command

## To Reproduce

1. Pull latest container
2. set env vars for server name and password
3. they are ignored

## Expected behavior

EITHER options that were previously added to the startup line should be set, or allow us to set our own startup command options

## Screenshots

My env vars being set, but the server is named "Default palworld server" and no password is set
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/98352913/613c3e92-4759-42b4-acac-22bedc54e755)

## Desktop (please complete the following information)

- OS: [e.g. Windows 10, Ubuntu, Debian]

## docker-compose.yml contents

```yaml
      containers:
      - name: palworld
        image: thijsvanloef/palworld-server-docker:latest
        env:
        - name: PLAYERS
          value: "16"
        - name: "COMMUNITY"
          value: "true"
        - name: "ADMIN_PASSWORD"
          value: "xxxxx"
        - name: "SERVER_PASSWORD"
          value: "xxxxx"
        - name: "SERVER_NAME"
          value: "xxxxxx"
        - name: "RCON_PORT"
          value: "25575"
        - name: "RCON_ENABLED"
          value: "true"
        - name: "BACKUP_CRON_EXPRESSION"
```

**Comment by thijsvanloef** [comment]
If you are able to please share the contents of your PalWorldSettings.ini.
Also are you using any special characters in your name/password?

**Comment by NobleKangaroo** [comment]
> If you are able to please share the contents of your PalWorldSettings.ini. Also are you using any special characters in your name/password?

You've done an amazing job with this container but it's now not working for my friends and I. Unfortunately the configuration is not loading now due to #203 which was actually not necessary, as you could provide spaces in the server name if you didn't provide quotes. Example (using Docker Swarm) which was working before #203:

```
version: '3.9'

x-nfs-driver-opts:
  &nfs-driver-opts
  type: nfs
  o: addr=nfs-server.example.com,nolock,tcp,hard

volumes:
  palworld_server:
    driver_opts:
      <<: *nfs-driver-opts
      device: ':/mnt/palworld_server'

services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PORT=8211
      - PLAYERS=20
      - COMMUNITY=true
      - SERVER_NAME=My Server Name Here
      - SERVER_DESCRIPTION=Pikachu, I choose you!
      - SERVER_PASSWORD=mypass
      - ADMIN_PASSWORD=theadminpass
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      # Customizations
      - DAYTIME_SPEEDRATE=0.25
      - NIGHTTIME_SPEEDRATE=3.0
      - PAL_EGG_DEFAULT_HATCHING_TIME=3.6
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    volumes:
      - palworld_server:/palworld
    deploy:
      placement:
        constraints:
          - node.labels.function == worker
        preferences:
          - spread: node.labels.zone
```

Could you maybe revert the change and re-build on Docker Hub until this is sorted out? At least that way it would be back to its original mostly- working state.

Thanks again, sorry this happened, hope to be able to play tonight.
