### ISSUE TITLE
RCON with adminPassword doesn't work in CLI

### ISSUE THREAD

**Issue by sethicis** [thijsvanloef/palworld-server-docker#214]
## Describe the bug

If you have an ADMIN_PASSWORD set for the server RCON will not accept any authorization.

I've tried wrapping the password in quotes, both double and single, without quotes, touching the `-p` switch, using the `--password` long form.  No matter what I try the RCON server always returns: `cli: execute: auth: rcon: authentication failed`.
If you set the `ADMIN_PASSWORD` to empty string, then the `rcon-cli` works as expected.  It's only when it is password protected that the CLI will not work.

## To Reproduce

1. Set the `ADMIN_PASSWORD` to something.
2. Start the docker instance.
3. Run `docker exec -it <containerID> rcon-cli --password <ADMIN_PASSWORD> info
4. See authorization failed message.

## Expected behavior

The provided admin password should be accepted if it matches what was set in as the docker environmental variable.

## Desktop (please complete the following information)

- Ubuntu 22.04.3 LTS
- Docker image 0.19.0

## docker-compose.yml contents

```yaml
version: '3.9'
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
     - PUID=1000
     - PGID=1000
     - PORT=8211 # Optional but recommended
     - PLAYERS=4 # Optional but recommended
     - MULTITHREADING=true
     - RCON_ENABLED=true
     - RCON_PORT=25575
     - ADMIN_PASSWORD='test1234'
     - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
     volumes:
      - ./game:/palworld/
  image_updater:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

## Important context

The world the server is running is a migrated single player save.

**Comment by sethicis** [comment]
I've experienced this issue with both 0.19.0 (today) and 0.17.0 (yesterday).

This might be important context, but I migrated a single player save to be the dedicated server world.  I noticed that when in game when I try to login to RCON via `/AdminPassword` it says there is no password set on the server.

This makes me wonder if the RCON password is not being set properly on the world config, which I heard is a thing for migrated saves.

**Comment by chickiyeah** [comment]
> I've experienced this issue with both 0.19.0 (today) and 0.17.0 (yesterday).
> 
> This might be important context, but I migrated a single player save to be the dedicated server world. I noticed that when in game when I try to login to RCON via `/AdminPassword` it says there is no password set on the server.
> 
> This makes me wonder if the RCON password is not being set properly on the world config, which I heard is a thing for migrated saves.

oh my server not update yesterday i think im using 2days ago version

**Comment by joebywan** [comment]
I had this same issue today, last night Rcon worked, now today it wasn't.  I've been using rcon to control whether the servers up or not by detecting players using it.

Anyway, rolled back to "thijsvanloef/palworld-server-docker:v0.18" and it is working in that version.

**Comment by thijsvanloef** [comment]
@sethicis Could you please confirm if the issue persists if you change your single quoted admin pass to double quotes?
     - ADMIN_PASSWORD='test1234'
     to
     - ADMIN_PASSWORD="test1234"

**Comment by joebywan** [comment]
Not the OP, but I had the issue just using your example docker-compose file locally, and also had it on AWS ECS Fargate.  My Fargate deployment is using terraform, using double quotes for the env vars, and the task definition on AWS doesn't have quotes (but takes JSON, so it'd be double quoted)

**Comment by bdelwood** [comment]
I have opened #223 to fix this.

**Comment by thijsvanloef** [comment]
Problem should be resolved in update 0.19.1 thanks to beomseok-park, please pull the latest image and check if your issue has been resolved.

**Comment by kometkamerat** [comment]
Issue not resolved I'm afraid, and now the server name is not set either (defaults to Default Palworld Server)

**Comment by thijsvanloef** [comment]
If you are still having trouble after updating, please remove your PalWorldSettings.ini and restart your container.

**Comment by sethicis** [comment]
@thijsvanloef , I pull the latest, deleted the `PalWorldSettings.ini` and restarted the container.

Unfortunately, the issue still persists.  I did also try changing the single quotes around the password string in the compose file to double; sadly, no effect.

```yaml
version: '3.9'
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
     - PUID=1000
     - PGID=1000
     - PORT=8211 # Optional but recommended
     - PLAYERS=4 # Optional but recommended
     - MULTITHREADING=true
     - RCON_ENABLED=true
     - RCON_PORT=25575
     - ADMIN_PASSWORD="test1234"
     - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
       # Enable the environment variables below if you have COMMUNITY=true
       # - SERVER_PASSWORD="worldofpals"
       # - SERVER_NAME="World of Pals"
    volumes:
      - ./game:/palworld/
  image_updater:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

### Current behavior on latest image pull:

<img width="589" alt="Screenshot 2024-01-30 at 5 43 04 PM" src="https://github.com/thijsvanloef/palworld-server-docker/assets/4684016/64e246f4-f0ed-4b37-856d-299bbe83c887">
