### ISSUE TITLE
stop and restarting server crashes save data

### ISSUE THREAD

**Issue by BugeonJo** [thijsvanloef/palworld-server-docker#267]
## Describe the bug

When i stop the server and restart server makes whole save data crash.

## To Reproduce

I used this command,

sudo docker stop palworld-server
and
sudo docker start palworld-server

then my charactor got lost, and character customization displayed.
This is not happen before 1.4.0.
The more annoying thing is that even if i roll-back the save file from the back-up save, the charactor couldn't come back. 

## Desktop (please complete the following information)

Google CloudServer
n2d-highmem-4

## docker-compose.yml contents

```yaml
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - PLAYERS=4 
      - SERVER_PASSWORD="" 
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - TZ="Asia/Seoul"
      - ADMIN_PASSWORD=""
      - COMMUNITY=false
      - SERVER_NAME="Server"
    volumes:
      - ./PalWorld:/palworld/

```
