### ISSUE TITLE
Server config cant modify

### ISSUE THREAD

**Issue by Clemv95** [thijsvanloef/palworld-server-docker#29]
I setup the server without community enable 
But now i set the environnement variables in the compose, and the server name doesnt change, nor the options
I dont understand why
Even when i set the PalWorldSettings.ini, and restart the server, it doesnt take the news parameters

**Comment by N33D0x** [comment]
Having the same issue. Copied the settings from the DefaultSetting file to the PalWorldSettings.ini and restarted the server. It does not apply the settings.

**Comment by Clemv95** [comment]
> Are you sure that you changed the right file and not the default template ?
> 
> ```
> This configuration file is a sample of the default server settings.
> Changes to this file will NOT be reflected on the server.
> To change the server settings, modify Pal/Saved/Config/LinuxServer/PalWorldSettings.ini.
> ```

100 % sure

**Comment by N33D0x** [comment]
Yeah, I did modify the given file "Pal/Saved/Config/LinuxServer/PalWorldSettings.ini". Restarted the server, yet I does not apply the settings. Also tried to comment the enviroment section in the compose file to prevent any clashing. That didn't help either.

**Comment by MoryCorp** [comment]
And have you tried ``docker compose down`` instead of stop ?

**Comment by N33D0x** [comment]
> And have you tried `docker compose down` instead of stop ?

Yes.

**Comment by thijsvanloef** [comment]
Environment Variables set in the docker-compose.yml override the settings in `PalWorldSettings.ini`. Please make sure that the environment variables are the same as in  `PalWorldSettings.ini`.

**Comment by SgtCanadian** [comment]
What about for settings that aren't listed as environmental variables? For example if I wanted to set this to false: "bEnableInvaderEnemy=True"?

**Comment by N33D0x** [comment]
> What about for settings that aren't listed as environmental variables? For example if I wanted to set this to false: "bEnableInvaderEnemy=True"?

Took a look in the container. The start.sh script hands over the enviromental variables. He would have to add every single variable to that script to make them available through docker compose.

Better option would be to to just let it run the PalServer.sh script and let it pull the config file.

@thijsvanloef  Please, correct me if I'm wrong.

**Comment by thijsvanloef** [comment]
@N33D0x Yeah, if you would like to change the PalWorldSettings.ini, best to set every env variable to empty

**Comment by SgtCanadian** [comment]
The PalWorldSettings.ini is completely empty - should we be putting the default settings.ini file and copying it and then removing all ENVs?

**Comment by N33D0x** [comment]
> @N33D0x Yeah, if you would like to change the PalWorldSettings.ini, best to set every env variable to empty

Actually that's what I tried. It seems the problem is that `STARTCOMMAND="./PalServer.sh -port=${PORT} -players=${PLAYERS}" hands over the variables by default even if they are empty. 

Probably it would be worth a try to hand them over as you do with the others and keep it like that `STARCOMMAND="./PalServer.sh`. That should make it possible to let the PalServer.sh pull the default settings or if applied the custom settings.

**Comment by gibsonje** [comment]
Also seeing PalWorldSettings.ini as completely empty.

**Comment by N33D0x** [comment]
> Also seeing PalWorldSettings.ini as completely empty.

It is empty by default. You need to copy the content from the default template into the PalWorldSettings.ini

**Comment by gibsonje** [comment]
What I'm seeing is changing the env vars doesn't seem to have any effect. I thought it would translate to PalWorldSettings but I haven't dove what the script does.

**Comment by Clemv95** [comment]
Even when changing PalWorldSettings.ini by hand, it doesnt take effect

**Comment by goodboyrobot** [comment]
I was able to get it to merge the settings correctly by making sure to not have the comments from the sample file at the top of my PalworldSettings.ini. Also doing docker compose down instead of docker compose stop as suggested above, not sure which fixed it

**Comment by MoryCorp** [comment]
> I was able to get it to merge the settings correctly by making sure to not have the comments from the sample file at the top of my PalworldSettings.ini. Also doing docker compose down instead of docker compose stop as suggested above, not sure which fixed it.
> 
> Specifically I was trying to get it to respect the death penalty setting

Thanks for the info mate.  
I'll try that !

**Comment by Clemv95** [comment]
> I was able to get it to merge the settings correctly by making sure to not have the comments from the sample file at the top of my PalworldSettings.ini. Also doing docker compose down instead of docker compose stop as suggested above, not sure which fixed it.
> 
> Specifically I was trying to get it to respect the death penalty setting

Thanks for the info 
If you change the server name, Can you verify that it also change in game ?

**Comment by MoryCorp** [comment]
> > I was able to get it to merge the settings correctly by making sure to not have the comments from the sample file at the top of my PalworldSettings.ini. Also doing docker compose down instead of docker compose stop as suggested above, not sure which fixed it.
> > Specifically I was trying to get it to respect the death penalty setting
> 
> Thanks for the info If you change the server name, Can you verify that it also change in game ?

This is my docker-compose.yml if it helps.
And everything works : 

```
services:
   palworld:
      image: thijsvanloef/palworld-server-docker
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PORT=8211
         - PLAYERS=16
         - MULTITHREADING=TRUE
         - COMMUNITY=TRUE
         - SERVER_PASSWORD="xxx"
         - SERVER_NAME="xxx"
         - ADMIN_PASSWORD="xxx"
      volumes:
         - ./game:/palworld/
   ```

**Comment by fynaltgn** [comment]
I have the image mounted, the server works, but I don't know how to open the files folder to load my save.

**Comment by MoryCorp** [comment]
> I have the image mounted, the server works, but I don't know how to open the files folder to load my save.

What do you mean ?

**Comment by fynaltgn** [comment]
I don't know how to access the save folder for example on the server.

**Comment by MoryCorp** [comment]
Oh you're using a Synology NAS ?
You probaby need to use a filer manager to access the volume of your docker container.  
That path should be : ``Pal/Saved/Config/LinuxServer/PalWorldSettings.ini``

**Comment by fynaltgn** [comment]
> Config

Yes, i use synology. 

I have tried file station and filezilla and it does not appear in either....

**Comment by JoycieC** [comment]
> > Config
> 
> Yes, i use synology.
> 
> I have tried file station and filezilla and it does not appear in either....
> 
> How do I get the files inside Pal to appear in Volume1/docker/palworld???????

The files will likely be somewhere around here
\@docker\btrfs\subvolumes
\@docker\containers

How did you get this working in Synology DSM's Docker Container? I'm struggling myself, could you share some tips for a Docker noob?

**Comment by fynaltgn** [comment]
> > > Config
> > 
> > 
> > Yes, i use synology.
> > I have tried file station and filezilla and it does not appear in either....
> > How do I get the files inside Pal to appear in Volume1/docker/palworld???????
> 
> The files will likely be somewhere around here @docker\btrfs\subvolumes @docker\containers
> 
> How did you get this working in Synology DSM's Docker Container? I'm struggling myself, could you share some tips for a Docker noob?

look for the image in docker, install it and in principle it is already installed but in this case the folder mapping does not appear correctly.

**Comment by dddddjent** [comment]
I moved my locally hosted game save to the dedicated server and deleting the WorldOption.sav file can make those env variables work.

**Comment by GregHilston** [comment]
> Environment Variables set in the docker-compose.yml override the settings in `PalWorldSettings.ini`. Please make sure that the environment variables are the same as in `PalWorldSettings.ini`.

Can you describe an example of how to use a docker compose service entry environment variable to set the field `DeathPenalty` to None? Would it just be:

```yaml
version: "3.7"

services:
  palworld:
    image: thijsvanloef/palworld-server-docker
    container_name: palworld
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      - PUID=99
      - PGID=100
      - PLAYERS=32
      - MULTITHREADING=TRUE
      - COMMUNITY=false
      - SERVER_NAME="Example"
      - ADMIN_PASSWORD="supersecretpassword"
      # I WANT TO PUT THE DEATHPENALTY HERE 
    volumes:
        - /home/ghilston/config/palworld:/palworld/
    restart: unless-stopped
```

I ask, as it would be lovely to have the configuration in my service entry, and not have to volume in a new `ini` file just for this game. 

My `./Pal/Saved/Config/LinuxServer/PalWorldSettings.ini` is also empty, like some folks mentioned above...
