### ISSUE TITLE
Broadcast is broken in rcon-cli

### ISSUE THREAD

**Issue by urbenlegend** [thijsvanloef/palworld-server-docker#296]
## Describe the bug
Broadcast seems broken when attempting to do it from rcon-cli. String seems to be truncated.
```
[user@arch-nas palworld-server-docker]$ docker-compose exec -it palworld rcon-cli
Waiting commands for 127.0.0.1:25575 (or type :q to exit)
> broadcast Testing please ignore
Broadcasted: Testing
> broadcast "Testing please ignore"
Broadcasted: "Testing
>
```

As you can see it seems to be truncated at the first space

## To Reproduce

1. Log into rcon-cli with `docker-compose exec -it palworld rcon-cli`
2. Attempt to broadcast a multi-word sentence
3. Notice that it gets truncated at the first space

## Expected behavior

Broadcast will send the whole message

## Actual behavior

Broadcast sends the first word and then stops

## OS information

- OS:  Arch Linux
- Palworld Version: 0.14.0
- Docker Image Version:  0.21.0

## Hardware information

- CPU:  Ryzen 5600G
- Memory:  32G 3200MT RAM

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: always
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_PASSWORD="<redacted>" # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="<redacted>"
         - COMMUNITY=false # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME="<redacted>"
         - SERVER_DESCRIPTION="<redacted>"
         # Custom game settings
         - PAL_EGG_DEFAULT_HATCHING_TIME=24
      volumes:
         - ./palworld:/palworld/
```
