### ISSUE TITLE
Changes to .env file not being changed in game / in PalWorldSettings.ini 

### ISSUE THREAD

**Issue by bigsby-exe** [thijsvanloef/palworld-server-docker#320]
## Describe the bug
I have `BASE_CAMP_WORKER_MAXNUM=20` set in my .env file however the PalWorldSettings.ini has it set to 15 and won't change when I change the env file.
Additionally if you change the PalWorldSettings.ini to set the base camp workers setting to 15 it will be reset the next time the container starts even if the env var has it set to 20. This file is in the persistent storage volume.

## To Reproduce
1. Run the container with default settings 
2. Change  `BASE_CAMP_WORKER_MAXNUM=20`  in your .env file
3. Restart the container 
4. observe the limit in game is still 15 and the PalWorldSettings.ini reflects this 
___
Manual change of the file
1. Stop the container 
2. Change the PalWorldSettings.ini to set `BASE_CAMP_WORKER_MAXNUM=20` 
3. Start the container 
4. Check the file again and it will have changed back to 15
## Expected behavior
Setting the value in the env file will set the value in game and also in the ini file 

## Actual behavior
Changes to env don't seem to do anything and changing the ini file manually rolls it back on next restart 

## docker-compose.yml contents

```yaml
version: "3.8"
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    env_file:
      - .env
    volumes:
      - /mnt/mediadisk/saves/palworld2:/palworld/
networks: {}
```

## Additional context
Extract from .env file 
```
ENABLE_AIM_ASSIST_KEYBOARD=False
DROP_ITEM_MAX_NUM=3000
DROP_ITEM_MAX_NUM_UNKO=100
BASE_CAMP_MAX_NUM=128
BASE_CAMP_WORKER_MAXNUM=20
DROP_ITEM_ALIVE_MAX_HOURS=1.000000
AUTO_RESET_GUILD_NO_ONLINE_PLAYERS=False
AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS=72.00000
```
