### ISSUE TITLE
read up i/o timeout

### ISSUE THREAD

**Issue by GregHilston** [thijsvanloef/palworld-server-docker#33]
## To Reproduce

1. `$ docker compose up -d palworld`

and you'll get this output:

```
[+] Running 1/1
 ✘ palworld Error                                                                                                             20.0s Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.1.3:53: read udp 192.168.1.124:50202->192.168.1.3:53: i/o timeout
```

## Expected behavior

The container comes up

## Screenshots

N/A

## Desktop (please complete the following information):

> Linux home-server 5.10.0-27-cloud-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux

## docker-compose.yml contents

```yaml
version: "3.7"

services:
  palworld:
    image: thijsvanloef/palworld-server-docker
    container_name: palworld
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PORT=8211
      - PLAYERS=16
      - MULTITHREADING=TRUE
      - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      # Enable the environment variables below if you have COMMUNITY=true
      - SERVER_PASSWORD=${SECRET_PALWORLD_SERVER_PASSWORD}
      - SERVER_NAME="Friends"
      - ADMIN_PASSWORD=${SECRET_PALWORLD_ADMIN_PASSWORD}
    volumes:
        - ${SERVER_CONFIG_BASE}/palworld:/palworld/
    restart: unless-stopped
```

(i have some environment variables set)
```

## Container/Host Logs

N/A

## Additional context

N/A
