### ISSUE TITLE
Servers keeps stopping every x time

### ISSUE THREAD

**Issue by skilledpt** [thijsvanloef/palworld-server-docker#339]
## Describe the bug

I disabled autobackup and auto restart on .env file and still  every few minutes server seems to crash or stop im not sure and i get this on console:
palworld-server  | Killed
palworld-server  | Sending Discord json: {"embeds":[{"title":"Server is stopped!                                  

## To Reproduce

Im not sure..

## Expected behavior

keep running

## Actual behavior

server stop every few minutes

## OS information

- OS:  ubuntu latest
- Palworld Version:  latest
- Docker Image Version:  latest

## Hardware information

- CPU:  4 core
- Memory:  8GB ram

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest # Use the latest-arm64 tag for arm64 hosts
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
        - 25575:25575/udp
      env_file:
         -  ./default.env
      volumes:
         - ./palworld:/palworld/
```

## Container/Host Logs

```log
palworld-server  | *****STARTING SERVER*****
palworld-server  | ./PalServer.sh -port=8211 -queryport=27015 EpicApp=PalServer                                                                         -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
palworld-server  | Sending Discord json: {"embeds":[{"title":"Server is started!                                                                        ","color":52224}]}
palworld-server  | Shutdown handler: initalize.
palworld-server  | Increasing per-process limit of core file size to infinity.
palworld-server  | - Existing per-process limit (soft=18446744073709551615, hard                                                                        =18446744073709551615) is enough for us (need only 18446744073709551615)
palworld-server  | [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
palworld-server  | CAppInfoCacheReadFromDiskThread took 0 milliseconds to initia                                                                        lize
palworld-server  | Setting breakpad minidump AppID = 2394010
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamUser021 bef                                                                        ore SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamFriends017                                                                         before SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERF                                                                        ACE_VERSION008 before SteamAPI_Init succeeded.
palworld-server  | [S_API FAIL] Tried to access Steam interface SteamNetworkingU                                                                        tils004 before SteamAPI_Init succeeded.
palworld-server  | Killed
palworld-server  | Sending Discord json: {"embeds":[{"title":"Server is stopped!                                                                        ","color":14614528}]}
palworld-server exited with code 0

```
