### ISSUE TITLE
Can not start palworld docker ( threadtools.cpp )

### ISSUE THREAD

**Issue by derbananenkoenig** [thijsvanloef/palworld-server-docker#352]
## Describe the bug

Server does not startup on first start: 

## OS information

- os centos 7 
- CentOS Linux release 7.9.2009 (Core)
- top - 21:47:24 up  1:15,  2 users,  load average: 0.61, 1.65, 1.77
Tasks: 177 total,   1 running, 176 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  3880076 total,  1204040 free,   476660 used,  2199376 buff/cache
KiB Swap:  1048572 total,  1048572 free,        0 used.  3135792 avail Mem 

## Hardware information

cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version 2.3.0
stepping	: 3
microcode	: 0x1
cpu MHz		: 3408.022
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl eagerfpu pni cx16 hypervisor lahf_lm abm rsb_ctxsw
bogomips	: 6816.04
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: QEMU Virtual CPU version 2.3.0
stepping	: 3
microcode	: 0x1
cpu MHz		: 3408.022
cache size	: 4096 KB
physical id	: 1
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 4
wp		: yes
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl eagerfpu pni cx16 hypervisor lahf_lm abm rsb_ctxsw
bogomips	: 6816.04
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

## docker-compose.yml contents

```yaml
# docker-compose.yml contents here
version: '2.2'
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1009
         - PGID=986
         - PORT=8211
         - PLAYERS6=
         - SERVER_PASSWORD="xxxxxxx"
         - MULTITHREADING=false
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="xxxxxxx"
         - COMMUNITY=true
         - SERVER_NAME="Haralds palserver"
      volumes:
         - ./data:/palworld/
```

## Container/Host Logs

```log
palworld-server | *****EXECUTING USERMOD*****
palworld-server | chown: cannot access '/home/steam/server/backup.sh': No such file or directory
palworld-server | chown: cannot access '/home/steam/server/restore.sh': No such file or directory
palworld-server | chown: cannot access '/home/steam/server/update.sh': No such file or directory
palworld-server | *****GENERATING CONFIGS*****
palworld-server | Compiling PalWorldSettings.ini...
palworld-server | Compiling PalWorldSettings.ini done!
palworld-server | *****STARTING INSTALL/UPDATE*****
palworld-server | tid(34) burning pthread_key_t == 0 so we never use it
palworld-server | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
palworld-server | Logging directory: '/home/steam/Steam/logs'
palworld-server | src/tier0/threadtools.cpp (4213) : Probably deadlock or failure waiting for thread to initialize.
palworld-server | [  0%] Checking for available updates...
palworld-server | Thread failed to initialize
palworld-server | src/tier0/threadtools.cpp (4213) : Probably deadlock or failure waiting for thread to initialize.
palworld-server | Thread failed to initialize

```
