### ISSUE TITLE
Server settings are not established.

### ISSUE THREAD

**Issue by dlashdk0723** [thijsvanloef/palworld-server-docker#357]
## Describe the bug

 No server modifications have been made since yesterday's image update. Previously, the game continued with the modifications.

## To Reproduce

1. Go to '...'  edit the settings after than stop the server, save them, and start the server again. but the settings will be reset.
## OS information

- OS:   Synology DSM
- Palworld Version:   0.1.4.1
- Docker Image Version:   latest (made 08-02-2024)

## Hardware information

- CPU:   quad core Intel J4125
- Memory:   18GB

## docker-compose.yml contents

```yaml
# docker-compose.yml contents here

services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s
    ports:
      - 8211:8211/udp
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - PLAYERS=32
      - MULTITHREADING=true
      - TZ=Asia/Seoul
      - COMMUNITY=false
      - SERVER_NAME="BBQ"
      - SERVER_PASSWORD="456"
      - ADMIN_PASSWORD="789"
    volumes:
      - ./:/palworld/
```

## Container/Host Logs

```log
<!-- Insert logs here -->
```
