### ISSUE TITLE
Container exits on MacOS / ARM64

### ISSUE THREAD

**Issue by jryanearl** [thijsvanloef/palworld-server-docker#366]
## Describe the bug
I am trying to start the latest-arm64 container on an M1 MacBook Pro that has Rancher Desktop installed and configured.  I'm using compose to try and bring it up, and I get an error.

## To Reproduce

1. On an Apple Silicon Mac, setup Rancher Desktop https://rancherdesktop.io
2. Choose the nerdctl replacement for docker.
3. 'nerdctl compose up' with the docker-compose.yaml provided below. 

## Expected behavior

Expect the container to run and PalWorld Server to update and run. 

## Actual behavior

It appears to call box86 instead of box64 when running steamcmd, I think.  I was looking at this late and I need help, I think there's something broken in the underlying steamcmd-arm64 image.

```
$ nerdctl compose up
INFO[0000] Creating network jre_default                 
INFO[0000] Ensuring image thijsvanloef/palworld-server-docker:latest-arm64 
INFO[0000] Creating container Pal1                      
INFO[0000] Attaching to logs                            
Pal1 |*****EXECUTING USERMOD*****
INFO[0000] Container "Pal1" exited                      
INFO[0000] All the containers have exited               
INFO[0000] Stopping containers (forcibly)               
INFO[0000] Stopping container Pal1                      
```

## OS information

- OS:  macOS Sonoma 14.3.1
- Palworld Version:  1.4.1.0 
- Docker Image Version:  
``` $ nerdctl version
Client:
 Version:	v1.7.3
 OS/Arch:	linux/arm64
 Git commit:	0a464409d0178e16d3d2bed36222937ec3fc9c77
 buildctl:
  Version:	v0.12.5
  GitCommit:	bac3f2b673f3f9d33e79046008e7a38e856b3dc6

Server:
 containerd:
  Version:	v1.7.2
  GitCommit:	0cae528dd6cb557f7201036e9f43420650207b58
 runc:
  Version:	1.1.12
  GitCommit:	51d5e94601ceffbbd85688df1c928ecccbfa4685
```

## Hardware information
<img width="229" alt="Screenshot 2024-02-11 at 1 41 27 PM" src="https://github.com/thijsvanloef/palworld-server-docker/assets/6120002/beb81174-5eb5-4682-9236-3c247028c466">

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest-arm64
      restart: always
      container_name: Pal1
      ports:
         - 25575:25575/tcp
         - 8215:8215/udp
         - 27015:27015/udp
      environment:
         - PUID=501
         - PGID=20
         - PUBLIC_IP=1.2.3.4
         - PUBLIC_PORT=8215
         - PORT=8215 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_PASSWORD="MacOS arm64 test" # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="arm64-test"
         - COMMUNITY=true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME="ARM64 on Mac PalWorld"
         - REGION="NA"
         - SERVER_DESCRIPTION="MacOS Container Test - M1 Pro 32GB"
         - BACKUP_ENABLED=true
         - IS_MULTIPLAYER=true
         - BACKUP_CRON_EXPRESION="0 0 * * *"
         - AUTO_UPDATE_ENABLED=true
         - AUTO_UPDATE_CRON_EXPRESSION="0 * * * *"
         - AUTO_UPDATE_WARN_MINUTES=30
         - AUTO_REBOOT_ENABLED=true
         - AUTO_REBOOT_WARN_MINUTES=15
         - AUTO_REBOOT_CRON_EXPRESSION="0 * * * *"
         - UPDATE_ON_BOOT=true
      volumes:
         - /Users/jre/palworld:/palworld/
```

## Container/Host Logs

```log
*****EXECUTING USERMOD*****
usermod: no changes
*****GENERATING CONFIGS*****
Compiling PalWorldSettings.ini...
Compiling PalWorldSettings.ini done!
*****STARTING INSTALL/UPDATE*****
/home/steam/steamcmd/steamcmd.sh: line 38: /usr/local/bin/box86: cannot execute binary file: Exec format error
cp: cannot stat './PalServer.sh': No such file or directory
sed: can't read ./PalServer-arm64.sh: No such file or directory
chmod: cannot access './PalServer-arm64.sh': No such file or directory
./PalServer-arm64.sh does not exist.
Try restarting with UPDATE_ON_BOOT=true
```
Note UPDATE_ON_BOOT=true is in the docker-compose.yaml

## Additional context

Rancher Desktop is a license unencumbered alternative to Docker Desktop and has better performance on MacOS supposedly.  Anyway, it's free to use.

**Comment by sonroyaalmerol** [comment]
Box86 being called when running steamcmd is expected. The steamcmd executable is a 32-bit application, which is incompatible with Box64.

`cannot execute binary file: Exec format error` is an error you usually see when running an executable built on one architecture but executed on another. It might also have something to do with the platform being unable to run 32-bit executables.

Sadly, I don't have an M1 or Rancher Desktop to help you test things but I've seen people successfully using the `latest-arm64` tag with Apple Silicon (#278). One thing I could suggest is try using the `latest` tag and let Rosetta do the emulation instead by adding `platform: linux/amd64` to your compose file like so:
```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      platform: linux/amd64
      restart: always
```
