### ISSUE TITLE
 did not find expected tag URI

### ISSUE THREAD

**Issue by Dylseat** [thijsvanloef/palworld-server-docker#368]
## Describe the bug

i can't use the rcon cli and the backup i have always this message "cli: config: parse file: yaml: line 3: did not find expected tag URI
"

## Screenshots

![Capture d'écran 2024-02-11 221738](https://github.com/thijsvanloef/palworld-server-docker/assets/23698300/c28de4b0-709e-44de-8182-e07db0dbb678)

## OS information

- OS:  <Synology DSM 923+, DSM 7.2.1-69057 Update 3>
- Palworld Version:  <latest>
- Docker Image Version:  <latest>

## Hardware information

- CPU:  AMD Ryzen R1600
- Memory:  32 GB

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=10 # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="********"
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
         #- SERVER_PASSWORD="*******"
         #- SERVER_NAME="Orange Cow"
         - BACKUP_CRON_EXPRESSION=0 */4 * * *
         - BACKUP_ENABLED=true
         - DELETE_OLD_BACKUPS=true
         - OLD_BACKUP_DAYS=30
      volumes:
         - ./:/palworld/
```
