### ISSUE TITLE
Having troubles updating PalWorldSettings.ini

### ISSUE THREAD

**Issue by BenWanLH** [thijsvanloef/palworld-server-docker#379]
## Describe the bug

Im running the palworld docker container on a Synology nas however whenever i edit the PalworldSetting.ini file, the settings get reset when i start the server. Whenever i edit the PalworldSettings.ini , i ensure that i stop the container before editing.

## To Reproduce

1. Stop Docker Contaienr
2. Update PalworldSettings.ini 
3. Start Docker Container

## Expected behavior

PalworldSettings.ini is updated when the server is up

## Actual behavior

PalworldSettings.ini is gets resetted

## OS information

- OS:  Synology DSM 7.2.1-69057 Update 3
- Palworld Version:  1.4.1

**Comment by Diyagi** [comment]
I believe you need to use the env option `DISABLE_GENERATE_SETTINGS=true`, otherwise `PalworldSettings.ini` will always be overwritten

**Comment by Diyagi** [comment]
Could you include your docker-compose.yml in this issue ?

**Comment by BenWanLH** [comment]
Hi @Diyagi 
```

services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest # Use the latest-arm64 tag for arm64 hosts
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         PUID: 1027
         PGID: 100
         PORT: 8211 # Optional but recommended
         PLAYERS: 16 # Optional but recommended
         SERVER_PASSWORD: "12345" # Optional but recommended
         MULTITHREADING: true
         RCON_ENABLED: true
         RCON_PORT: 25575
         TZ: "UTC+8"
         ADMIN_PASSWORD: "12345"
         COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         SERVER_NAME: "Palworld on NAS"
         SERVER_DESCRIPTION: "Palworld hosted on NAS"
         PAL_EGG_DEFAULT_HATCHING_TIME: 1
         BASE_CAMP_WORKER_MAX_NUM: 20
         DISABLE_GENERATE_SETTINGS: true
      volumes:
         - ./data:/palworld/

```
