### ISSUE TITLE
Environment variable PUBLIC_PORT does not apply to PalWorldSettings.ini.

### ISSUE THREAD

**Issue by MusclePr** [thijsvanloef/palworld-server-docker#389]
## Describe the bug

Environment variable **PUBLIC_PORT** does not apply to **PublicPort** of PalWorldSettings.ini.

## To Reproduce

1. Set PUBLIC_PORT to a value other than 8211 in enviroments in docker-compose.yml.
```yaml
    environment:
      PUBLIC_PORT: 8212
```
2. run docker
```sh
docker compose up -d
```
4. see PublicPort of PalWorldSettings.ini
```sh
sed -nre 's/.*(PublicPort=\w+).*/\1/p' palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
```
5. always `PublicPort=8211`

## Expected behavior

docker-compose.yml
```yaml
    environment:
      PUBLIC_PORT: 8212
```
PalWorldSettings.ini
```ini
PublicPort=8212
```

## Actual behavior

docker-compose.yml
```yaml
    environment:
      PUBLIC_PORT: 8212
```
PalWorldSettings.ini
```ini
PublicPort=8211
```

## Screenshots

nothing.

## OS information

- OS:  Ubuntu 22.04 LTS
- Palworld Version:  0.1.4.1
- Docker Image Version:  0.25.0

## Hardware information

- CPU:  Intel Core i9 13900K
- Memory:  DDR5 192GB

## docker-compose.yml contents

```yaml
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211  # Optional but recommended
      PLAYERS: 16  # Optional but recommended
      SERVER_PASSWORD: "worldofpals"  # Optional but recommended
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      TZ: "UTC"
      ADMIN_PASSWORD: "adminPasswordHere"
      COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "World of Pals"
      SERVER_DESCRIPTION: "palworld-server-docker by Thijs van Loef"
      PUBLIC_PORT: 8212
    volumes:
      - ./palworld:/palworld/
```

## Container/Host Logs

```log
*****EXECUTING USERMOD*****
usermod: no changes
*****STARTING INSTALL/UPDATE*****
tid(25) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
tid(37) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...OK
"@sSteamCmdForcePlatformType" = "linux"
"@sSteamCmdForcePlatformBitness" = "64"

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 25.28 (571405715 / 2260368082)
 Update state (0x5) verifying install, progress: 52.01 (1175687776 / 2260368082)
 Update state (0x5) verifying install, progress: 78.91 (1783698316 / 2260368082)
Success! App '2394010' fully installed.
*****GENERATING CONFIG*****
***Using Env vars to create PalWorldSettings.ini***
Compiling PalWorldSettings.ini...
Compiling PalWorldSettings.ini done!
BACKUP_ENABLED=true
*****STARTING SERVER*****
./PalServer.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-02-14T03:33:46Z" level=info msg="read crontab: /home/steam/server/crontab"
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Shutdown handler: initalize.
Increasing per-process limit of core file size to infinity.
CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```

## Additional context

This only causes problems when selecting from a server list.
