### ISSUE TITLE
Problems with modifying egg hatching time env

### ISSUE THREAD

**Issue by clyde0813** [thijsvanloef/palworld-server-docker#446]
There is an issue with modifying PAL_EGG_DEFAULT_HATCHING_TIME. 
When attempting to set the default value from 72 hours to 0 hours, there is a problem where any value equal to or less than 1 is forced to be set as 1. I wonder if it is forcibly set to 1 because it cannot be set to less than 1 hour.

Even when setting PAL_EGG_DEFAULT_HATCHING_TIME to 0 in the Docker environment, it remains set to 1 in PalGameWorldSettings.

Is there no other way but to modify and apply it within the Docker container?

**Comment by Diyagi** [comment]
I have mine set to 0 and its working, can you share your docker compose ?

**Comment by clyde0813** [comment]
Here's my compose.yaml. Did I write something wrong?
```
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211 
      PLAYERS: 8
      SERVER_PASSWORD: ****
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      TZ: UTC
      ADMIN_PASSWORD: ****
      COMMUNITY: false
      SERVER_NAME: ****
      SERVER_DESCRIPTION: ****
      PAL_EGG_DEFAULT_HATCHING_TIME: 0
    volumes:
      - ./palworld:/palworld/
networks: {}
```
