### ISSUE TITLE
Server fails to start after updating Docker to v0.29

### ISSUE THREAD

**Issue by CruiseTian** [thijsvanloef/palworld-server-docker#465]
## Describe the bug

After updating to the latest version (v0.29) of Docker, the server fails to start. The stderr.txt file in the Steam/log folder shows the following error: `src/tier0/threadtools.cpp (3830) : Assertion Failed: Failed to create thread (error 0x1)`, The complete content in stderr.txt is as follows:
```txt
02/28 00:10:26 Init: Installing breakpad exception handler for appid(steam)/version(1705108307)/tid(31)
src/tier0/threadtools.cpp (3830) : Assertion Failed: Failed to create thread (error 0x1)
assert_20240228001026_4.dmp[34]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240228001026_4.dmp
assert_20240228001026_4.dmp[34]: Finished uploading minidump (out-of-process): success = no
assert_20240228001026_4.dmp[34]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20240228001026_4.dmp[34]: file ''/tmp/dumps/assert_20240228001026_4.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
```

## To Reproduce

1. Pull the latest image
2. Backup the old server using `docker exec palworld-server backup`
3. Recreate the new container using `docker-compose up -d`

## Expected behavior

Server restart successfully.

## Actual behavior

Server can not start and steamcmd get `Assertion Failed` error

## Screenshots

+ **container status**
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/50127078/59c8202c-ad82-40b2-8273-f8666d7a497c)

+ **container log**
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/50127078/b9717a0a-2b2b-4866-a045-d4a45a81bf86)

+ **stderr log**
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/50127078/43e4e51a-4760-454f-b55b-4d7dddba9870)

## OS information

- OS:  Linux debian11 5.10.0-8-amd64 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
- Palworld Version:  0.1.5.0
- Docker Image Version:  latest(v0.29)

## Hardware information

- CPU:  4 core Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
- Memory:  12GB

## docker-compose.yml contents

```yaml
version: '3'
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
        - 25575:25575/tcp
      environment:
         - TZ=Asia/Shanghai
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=8 # Optional but recommended
         - MULTITHREADING=true
         - PLAYER_STOMACH_DECREASE_RATE=0.200000
         - PALYER_STAMINA_DECREASE_RATE=0.200000
         - PLAYER_AUTO_HP_REGEN_RATE=2.000000
         - PAL_STOMACH_DECREASE_RATE=0.200000
         - PAL_STAMINA_DECREASE_RATE=0.200000
         - PAL_AUTO_HP_REGEN_RATE=2.000000
         - COLLECTION_OBJECT_RESPAWN_SPEED_RATE=0.500000
         - BASE_CAMP_WORKER_MAXNUM=20
         - PAL_EGG_DEFAULT_HATCHING_TIME=0.000000
         - DEATH_PENALTY="None"
         - WORK_SPEED_RATE=2.000000
         - UPDATE_ON_BOOT=false
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD="********"
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME="********"
         - BACKUP_CRON_EXPRESION=0 4 * * *
         - BACKUP_ENABLED=true
         - DELETE_OLD_BACKUPS=true
         - OLD_BACKUP_DAYS=7
         - AUTO_UPDATE_CRON_EXPRESSION=0 */2 * * *
         - AUTO_UPDATE_ENABLED=true
         - AUTO_UPDATE_WARN_MINUTES=15
      volumes:
         - ./palworld:/palworld/
```

## Container/Host Logs

```log
****EXECUTING USERMOD****
usermod: no changes
Server installation not detected.
****Starting Installation****
tid(31) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
```

## Additional context

My previously used docker image version is v0.24.0, and it works perfect.
