### ISSUE TITLE
Unable to edit LinuxServer config when pulling the latest version (v0.15.1) by palworld.

### ISSUE THREAD

**Issue by zyknow** [thijsvanloef/palworld-server-docker#488]
## Describe the bug

Use "docker-compose pull" to get the latest version, but starting the server always resets the LinuxServer/PalWorldSettings.ini.

## To Reproduce

1. docker-compose down
2. edit LinuxServer/PalWorldSettings.ini
3. docker-compose up -d

## Expected behavior

Linux server/PalWorldSettings.ini will not be reset

## Actual behavior

Linux server/PalWorldSettings.ini has been reset

## OS information

- OS:  
- Palworld Version:  
- Docker Image Version:  
Ubuntu 22.04.3 LTS
Docker version 25.0.1
Palworld Version: 0.15.1

## Hardware information
8 core 32G

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_PASSWORD="mainloadpw" # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="mainloadpassword^."
         - COMMUNITY=true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         - SERVER_NAME="MainLoad_China_Server"
      volumes:
         - ./palworld:/palworld/
```

## Container/Host Logs

```log
****EXECUTING USERMOD****
usermod: no changes
****Checking for new update****
Current Version: 2815085007637542021
The Server is up to date!
****GENERATING CONFIG****
Using Env vars to create PalWorldSettings.ini
****Compiling PalWorldSettings.ini****
Compiling PalWorldSettings.ini done!
****GENERATING CRONTAB****
BACKUP_ENABLED=true
Adding cronjob for auto backups
Cronjobs started
****Starting Server****
./PalServer.sh -queryport=27015
time="2024-03-04T06:04:54Z" level=info msg="read crontab: /home/steam/server/crontab"
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Shutdown handler: initalize.
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
Waiting for RCON port to open to show player logging...
cli: password is not set: to set password add -p password
cli: password is not set: to set password add -p password
cli: password is not set: to set password add -p password
cli: password is not set: to set password add -p password
cli: password is not set: to set password add -p password
cli: password is not set: to set password add -p password
cli: password is not set: to set password add -p password
cli: password is not set: to set password add -p password
cli: password is not set: to set password add -p password
```
