### ISSUE TITLE
many errors `cli: execute: rcon: read tcp 127.0.0.1:PORT->127.0.0.1:25575: i/o timeout` and disconnected

### ISSUE THREAD

**Issue by DesistDaydream** [thijsvanloef/palworld-server-docker#492]
## Describe the bug

After the first player logs in, the following content will continue to be output

```bash
cli: execute: rcon: read tcp 127.0.0.1:46026->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:44320->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:56154->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:49222->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:47212->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:56456->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:49470->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:52900->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:42510->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:39202->127.0.0.1:25575: i/o timeout
cli: execute: rcon: read tcp 127.0.0.1:60108->127.0.0.1:25575: i/o timeout
......MORE AND MORE
```

The second player to log in disconnects after a while in the game

## To Reproduce

1. run cmd

```bash
docker compose up
```

## Expected behavior

1. There shouldn't be so many error logs
2. The second player should not disconnect at irregular intervals

## Actual behavior

[Describe the bug](Describe%20the%20bug)

## Screenshots

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/39847025/9675d161-7704-4c39-9f1a-ffbf00373a08)

## OS information

- OS:  Ubuntu 2204
- Palworld Version:  0.1.5.1
- Docker Image Version:  latest, IMAGE ID: 256899e761df
  - In fact, it started from a certain version last week, I forgot which one it was.

## Hardware information

- CPU:  Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
- Memory:  32G DDR4

## docker-compose.yml contents

```yaml
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server-home
    stop_grace_period: 30s
    ports:
      - 8213:8211/udp
      - 27017:27015/udp  # Required if you want your server to show up in the community servers tab
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211  # Optional but recommended
      PLAYERS: 4  # Optional but recommended
      SERVER_PASSWORD: "home"  # Optional but recommended
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      TZ: "CST"
      ADMIN_PASSWORD: "home"
      COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "HomeServer"
      SERVER_DESCRIPTION: "Home PalWorld"
    volumes:
      - ./palworld:/palworld/
```

## Container/Host Logs

[Describe the bug](#Describe%20the%20bug)

## Additional context

None
