### ISSUE TITLE
Error in documentation for starting docker

### ISSUE THREAD

**Issue by T-h-o-r-p-e** [thijsvanloef/palworld-server-docker#499]
## To Reproduce

Steps to reproduce the behaviour:

1. following the documentation as is currently written;
2. typing `docker compose up -d`
3. press enter
4. get error `unknown shorthand flag: 'd' in -d`

## Actual behaviour

`unknown shorthand flag: 'd' in -d`

## OS information (IMPORTANT)

- OS:  Ubuntu
- Palworld Version:  N/A
- Docker Image Version:  0.32.0

## Hardware information (IMPORTANT)

N/A

## docker-compose.yml contents (IMPORTANT)

```yaml
---
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211  # Optional but recommended
      PLAYERS: 32  # Optional but recommended
      SERVER_PASSWORD: ""  # Optional but recommended
      MULTITHREADING: "true"
      RCON_ENABLED: "true"
      RCON_PORT: 25575
      TZ: "UTC"
      ADMIN_PASSWORD: ""
      COMMUNITY: "false"  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "Arm-Test"
      SERVER_DESCRIPTION: "Work God Dammit"
      EXP_RATE: 1.5
      PAL_CAPTURE_RATE: 1.5
      PAL_SPAWN_NUM_RATE: 1.5
      PLAYER_AUTO_HP_REGEN_RATE: 1.25
      PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP: 5
      PAL_AUTO_HP_REGEN_RATE: 1.25
      PAL_AUTO_HP_REGEN_RATE_IN_SLEEP: 5
      BUILD_OBJECT_DAMAGE_RATE: 0.25
      BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: 0
      COLLECTION_DROP_RATE: 1.5
      COLLECTION_OBJECT_RESPAWN_SPEED_RATE: 0.5
      ENEMY_DROP_ITEM_RATE: 1.5
      DEATH_PENALTY: 1
      BASE_CAMP_WORKER_MAX_NUM: 20
      GUILD_PLAYER_MAX_NUM: 32
      PAL_EGG_DEFAULT_HATCHING_TIME: 0.5
      WORK_SPEED_RATE: 2
      ENABLE_NON_LOGIN_PENALTY: "false"
      COOP_PLAYER_MAX_NUM: 32
    volumes:
      - ./palworld:/palworld/

```

## Bug Report Checklist

- [y] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [y] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [y] I have included all relevant information required above.
- [n - I don't know the first thing about docker, hence why I was following the documentation exactly as it was written] I am willing to fix this bug
