### ISSUE TITLE
port modify doesn't work?

### ISSUE THREAD

**Issue by RoryKirsi** [thijsvanloef/palworld-server-docker#51]
## Describe the bug

Hi Thijs, thanks for your docker. I have a question about the port change.

Modify docker-compose.yml -> 
```
......
       ports:
-        - 8211:8211/udp
+        - 8888:8211/udp
         - 27015:27015/udp
       environment:
          - PUID=1000
          - PGID=1000
-         - PORT=8211 # Optional but recommended
+         - PORT=8888 # Optional but recommended
          - PLAYERS=16 # Optional but recommended
......
```

But it doesn't work if I connect with the port in the game. Am I setting wrong? 
## To Reproduce

**After modify I run**
`docker compose up -d`

## Expected behavior

Connect the game with the url <ip>:8888

**Comment by thijsvanloef** [comment]
Hi! There seems to be a configration error, you can either use one of these:

```yaml
       ports:
         - 8888:8211/udp
         - 27015:27015/udp
       environment:
          - PUID=1000
          - PGID=1000
          - PORT=8211 # Optional but recommended
          - PLAYERS=16 # Optional but recommended
```
OR
```yaml
       ports:
         - 8888:8888/udp
         - 27015:27015/udp
       environment:
          - PUID=1000
          - PGID=1000
          - PORT=8888 # Optional but recommended
          - PLAYERS=16 # Optional but recommended
```
If you want to run the server on port 8888
