### ISSUE TITLE
Server suddenly assigns new Steam/Player IDs 

### ISSUE THREAD

**Issue by Wasilewskiii** [thijsvanloef/palworld-server-docker#525]
## Describe the bug

After updating to todays patch, our server suddenly started to assign different Player/Steam ID´s to people which lead to them having to create new characters because the server thinks they are new players. I cannot see where the issue comes from so far. First I thought it might be connected to just 1 or 2 steam accounts, but it happens to all players on the server. When making a new character and exploring the server, everything that was built and all pals in the bases are still there.

I have now written in multiple places. Nobody was able to help and I´ve seen only a few people having the same issue. I am hoping someone who is deep into the topic might know what is causing it and if it has something to do with this repo at all. 

## To Reproduce
Restart the server, update to v0.2.0.6 and join the server.

## Expected behavior
Players should be able to log in and get their (old) ID assigned so they´re able to play their characters.

## Actual behavior
Players get new IDs assigned and they have to create new characters.

## OS information (IMPORTANT)

- OS:  Ubuntu 22.04
- Palworld Version:   0.2.0.6 
- Docker Image Version:  0.35.0

## Hardware information (IMPORTANT)

- CPU:  Intel Core i7-8700 6 Core
- Memory:  64 DDR4

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
---
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      env_file:
         -  .env
      volumes:
         - ./palworld:/palworld/
```

</details>

## Bug Report Checklist

- [X] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [X] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [X] I have included all relevant information required above.
