### ISSUE TITLE
 a way to change generall game world settings 

### ISSUE THREAD

**Issue by ilco3** [thijsvanloef/palworld-server-docker#53]
i would love a way to settings for the gameworld ( PalWorldSettings )

currently have no idea how to find the file used to configure this

wouuld love to to fo example set item drop on death to off /or set a hasher penalty

**Comment by pingwutm-iip** [comment]
+1

**Comment by MrSnake0208** [comment]
You can edit it at "YourPath/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini", and the example config is at "YourPath/DefaultPalWorldSettings.ini"

**Comment by fynaltgn** [comment]
> You can edit it at "YourPath/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini", and the example config is at "YourPath/DefaultPalWorldSettings.ini"
I modified the .ini file in "YourPath/DefaultPalWorldSettings.ini" and when you save and close it defaults to default.

I check the "YourPath/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini" but the file is empty?

Has anyone else migrated the save from another server to their dedicated server and lost the map progression?

**Comment by MrSnake0208** [comment]
> > You can edit it at "YourPath/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini", and the example config is at "YourPath/DefaultPalWorldSettings.ini"
> > I modified the .ini file in "YourPath/DefaultPalWorldSettings.ini" and when you save and close it defaults to default.
> 
> I check the "YourPath/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini" but the file is empty?
> 
> Has anyone else migrated the save from another server to their dedicated server and lost the map progression?

You can copy config at "YourPath/DefaultPalWorldSettings.ini", this is the example config.

**Comment by thijsvanloef** [comment]
I have added the following documentation: https://github.com/thijsvanloef/palworld-server-docker?tab=readme-ov-file#editing-server-settings 
@fynaltgn Does this help you set the correct settings?

**Comment by dotlogix** [comment]
For me it does not the file is not recreated and the setting don't apply.
I added a server name and password. The password is now there but I don't see my server in the community list and can not join the server anymore because the ip login does not allow to enter a password.

**Comment by thijsvanloef** [comment]
@dotlogix please make sure you have pulled the latest image before starting:

`docker compose pull`

**Comment by dotlogix** [comment]
@thijsvanloef Same deal unfortunately I don't see my server in the server list and can not login if I set a server password using the IP

**Comment by thijsvanloef** [comment]
@dotlogix can you try this workaround:


- Open Community Servers list.
- Click on any Passworded Server
- Enter the password for "your" server
- Click Ok, then Click No
- Use Direct Connect with your IP:Port to your server

**Comment by dotlogix** [comment]
This actually worked, however it is still weird why it is not showing up in the server list.
This is my compose file:
```
services:
   palworld:
      image: thijsvanloef/palworld-server-docker
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PORT=8211
         - PUID=1000
         - PGID=1000
         - PLAYERS=16
         - MULTITHREADING=FALSE
         - COMMUNITY=TRUE
         - SERVER_PASSWORD="****"
         - SERVER_NAME="****"
         - ADMIN_PASSWORD="****"
      volumes:
         - /opt/docker/palworld/data:/palworld/
```
And this is my ini:
```
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=10.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,PublicPort=8211,PublicIP="",RCONEnabled=False,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
```

Am I missing sth?
