### ISSUE TITLE
Can't change ENV parameters in docker-compose.yml (PalWorldSettings.ini doesn't work)

### ISSUE THREAD

**Issue by Paddy32810** [thijsvanloef/palworld-server-docker#545]
## Describe the bug

I add env parameters in docker-compose.yml, also through stack editor, and it's not taken into account. I'm trying on palworld to get egg hatching timer down.

## To Reproduce

Steps to reproduce the behavior: change docker-compose.yml and it doesn't work

## Expected behavior

parameters get update

## Screenshots

![image](https://github.com/thijsvanloef/palworld-server-docker/assets/50557539/c40e442a-d2bc-4f63-b1e1-04e6405cb04c)

## OS information (IMPORTANT)

Using Marius tutorial to create the server. https://mariushosting.com/how-to-install-palworld-server-on-your-synology-nas/

it works really well

## Hardware information (IMPORTANT)

DS923+

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
version: "3.9"
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest # Use :latest-arm64 tag instead of :latest for arm64 NAS
      restart: on-failure:5
      container_name: Palworld-Server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
        - PUID=1026
        - PGID=100
        - PORT=8211
        - PLAYERS=16
        - SERVER_PASSWORD=xxxxxxxxxxxxxxxxx
        - MULTITHREADING=true
        - RCON_ENABLED=true
        - RCON_PORT=25575
        - TZ=Europe/Paris
        - ADMIN_PASSWORD=xxxxxxxxxxxxxxxxx # You can secure the access to a server by using the admin password.
        - COMMUNITY=false  # Enable this with true if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD above.
        - SERVER_NAME=xxxxxxxxxxxxxxxxx
        - SERVER_DESCRIPTION=xxxxxxxxxxxxxxxxx
        - BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=0.00000
        - DEATH_PENALTY=Item
        - PAL_EGG_DEFAULT_HATCHING_TIME=0.00000
      volumes:
         - /volume1/docker/palworld-server:/palworld:rw
</details>
```

## Container/Host Logs (IMPORTANT)

<details><summary>Logs</summary>

```log
<!-- Insert logs here -->
```

</details>

## Bug Report Checklist

- [x] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [ ] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have included all relevant information required above.
- [ ] I am willing to fix this bug
