### ISSUE TITLE
steamcmd missing file permissions to update palworld

### ISSUE THREAD

**Issue by dichromatic** [thijsvanloef/palworld-server-docker#551]
## Describe the bug

Palworld unable to update on container restart, steamcmd gives me a missing file permissions error. Have tried recreating the container to the same result. Not exactly sure what's causing the permissions error, I haven't touched the container other than restarting it for game updates. Have not touched PUID or GUID either. 

## To Reproduce

1. Restart container with `docker-compose up`
2. Wait for steamcmd to update Palworld

## Expected behavior

Palworld should have updated.

## Actual behavior

On startup, it gives me "ERROR! Failed to install app '2394010' (Missing file permissions)".

## Screenshots

N/A

## OS information (IMPORTANT)

- OS:  Debian 11 bullseye
- Palworld Version:  0.2.1.0
- Docker Image Version: latest 0.37.1

## Hardware information (IMPORTANT)

- CPU:  Intel i3-12100F
- Memory:  32gb DDR4

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
version: '3'
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 10000:10000/udp
        - 27015:27015/udp
      environment:
        #- ADMIN_PASSWORD="pword"
         - SERVER_NAME="name"
         - PORT=10000
         - PLAYERS=16
         - MULTITHREADING=true
         - UPDATE_ON_BOOT=true
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
         # - SERVER_PASSWORD="worldofpals"
         # - SERVER_NAME="World of Pals"
         # - ADMIN_PASSWORD="someAdminPassword"
      volumes:
         - ./palworld:/palworld/
```

</details>

## Container/Host Logs (IMPORTANT)

<details><summary>Logs</summary>

```log
palworld-server | Redirecting stderr to '/root/Steam/logs/stderr.txt'
palworld-server | Logging directory: '/root/Steam/logs'
palworld-server | [  0%] Checking for available updates...
palworld-server | [----] Verifying installation...
palworld-server | Steam Console Client (c) Valve Corporation - version 1718305764
palworld-server | -- type 'quit' to exit --
palworld-server | Loading Steam API...OK
palworld-server |
palworld-server | Connecting anonymously to Steam Public...OK
palworld-server | Waiting for client config...OK
palworld-server | Waiting for user info...OK
palworld-server | ERROR! Failed to install app '2394010' (Missing file permissions)
palworld-server | ./PalServer.sh -port=10000 -players=16 -servername="name" -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
palworld-server | *****STARTING SERVER*****The file already exists: /palworld/Pal/Binaries/Linux/steamclient.so
palworld-server | [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
palworld-server | CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
palworld-server | Setting breakpad minidump AppID = 2394010
palworld-server | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
palworld-server | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
palworld-server | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
palworld-server | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```

</details>

## Additional context

Running on a home debian server.

## Bug Report Checklist

- [X] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [X] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [X] I have included all relevant information required above.
- [X] I am willing to fix this bug

**Comment by nevesm** [comment]
I am facing the same issue with appId '730'

**Comment by thijsvanloef** [comment]
@dichromatic Can you show the permissions on your mounted folder? 
```bash
ls -al ./palworld
```

**Comment by dichromatic** [comment]
```log
❯ ls -al palworld
total 44648
drwxr-xr-x 7 rumi rumi     4096 Jun 16 20:09 .
drwxr-xr-x 3 rumi rumi     4096 Jan 24 16:32 ..
-rwxr-xr-x 1 rumi rumi     2087 Apr  5 22:45 DefaultPalWorldSettings.ini
-rwxr--r-- 1 rumi rumi     4096 Jan 24 16:32 ._.DS_Store
-rwxr--r-- 1 rumi rumi     8196 Jan 24 16:33 .DS_Store
drwxr-xr-x 6 rumi rumi     4096 Apr  5 22:47 Engine
drwxr-xr-x 2 rumi rumi     4096 Jan 21 16:22 linux64
-rwxr-xr-x 1 rumi rumi      438 Apr  5 22:45 Manifest_DebugFiles_Linux.txt
-rwxr-xr-x 1 rumi rumi     3031 Apr  5 22:45 Manifest_NonUFSFiles_Linux.txt
-rwxr-xr-x 1 rumi rumi  7990849 Apr  5 22:45 Manifest_UFSFiles_Linux.txt
drwxr-xr-x 7 rumi rumi     4096 Jan 24 16:33 Pal
-rwxr-xr-x 1 rumi rumi      815 Apr  5 22:45 PalServer.sh
drwxr-xr-x 3 rumi rumi     4096 Jun 16 20:11 steamapps
drwxr-xr-x 4 rumi rumi     4096 Apr  7 04:03 steamapps_backup
-rwxr-xr-x 1 rumi rumi 37665020 Jan 21 16:18 steamclient.so
```

rumi being my user.

**Comment by thijsvanloef** [comment]
You might want to try the following command:

```bash
id
```
Should get an output like this:
```bash
uid=1000(thijs) gid=1000(thijs)
```
And then run your container with:
```yaml
    environment:
      PUID: 1000 (your UID)
      PGID: 1000 (your GID)
```
