### ISSUE TITLE
ARM64 Exec format error

### ISSUE THREAD

**Issue by tinducvo** [thijsvanloef/palworld-server-docker#579]
Using 0.38.1/0.38.2, I get the following on Oracle Cloud ARM64:
./PalServer-arm64.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-07-10T19:17:15Z" level=info msg="read crontab: /home/steam/server/crontab"
The file has been successfully copied: /palworld/linux64/steamclient.so -> /palworld/Pal/Binaries/Linux/steamclient.so
./PalServer-arm64.sh: 21: /palworld/Pal/Binaries/Linux/PalServer-Linux-Shipping: Exec format error

I also noticed the README references ARM64_DEVICE added in 0.39.0, which is unreleased.

---

The container works fine if I downgrade to 0.38.0.

**Comment by sonroyaalmerol** [comment]
Hi! Please follow the issue template as much as possible next time. We'll need **OS, Hardware information** (see the details needed from the template) and **docker-compose.yml contents** (don't forget to remove secrets).

There has been no significant changes at all from 0.38.0 to 0.38.1 that would affect ARM64. It's all config/documentation additions only based from the diff: https://github.com/thijsvanloef/palworld-server-docker/compare/0.38.0...0.38.1

Most of the ARM64 changes are between 0.38.1 and 0.38.2 so that doesn't seem right. I believe our unit tests and builds for ARM64 are also executed on an Oracle Cloud ARM64 instance as well so there must be something else on your setup.

Also, vars labeled for 0.39.0 was released on 0.38.2, just a typo. We'll fix it soon. Thanks for letting us know!

**Comment by tinducvo** [comment]
## Describe the bug

With the following configuration, I can start fresh with 0.38.0 then update to 0.38.2.

However, with my save data, when I try to upgrade to 0.38.1/0.38.2 or manually copy my palworld/Pal/Saved folder to the working docker container, I get the following:

```
/usr/local/bin/box64: line 32:    92 Segmentation fault      (core dumped) "$BINARY_PATH" "$@"
```

## OS information (IMPORTANT)

- OS: Ubuntu 22.04.4 LTS
- Kernel: 6.5.0-1025-oracle
- Palworld Version: v0.3.3.55731
- Docker Image Version: 27.0.3, build 7d4bcd8

## Hardware information (IMPORTANT)

- CPU: AMPERE ALTRA Q80-30 w/ 4 OCPUs 
- Memory: 24GB DDR4

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:v0.38.2
      restart: unless-stopped
      ports:
        - 8211:8211/udp # Game
        - 27015:27015/udp # Query
        - 8212:8212/tcp # REST API
        - 25575:25575/tcp # RCON
      environment:
         - ARM_COMPATIBILITY_MODE=true
         - PUID=1001
         - PGID=1001
         - PLAYERS=8
         - SERVER_PASSWORD=testing
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - REST_API_ENABLED=true
         - ADMIN_PASSWORD=moretesting
         - COMMUNITY=true
         - SERVER_NAME=TestPals
         - SERVER_DESCRIPTION=We love testing.
         - REGION=NA
         - UPDATE_ON_BOOT=true
         - PAL_EGG_DEFAULT_HATCHING_TIME=36.000000
         - ENABLE_NON_LOGIN_PENALTY=false
         - DISABLE_GENERATE_ENGINE=false
         - LAN_SERVER_MAX_TICK_RATE=60
         - NET_SERVER_MAX_TICK_RATE=60
         - CONFIGURED_INTERNET_SPEED=104857600
         - CONFIGURED_LAN_SPEED=104857600
         - MAX_CLIENT_RATE=104857600
         - MAX_INTERNET_CLIENT_RATE=104857600
         - SMOOTH_FRAME_RATE=true
         - SMOOTH_FRAME_RATE_LOWER_LIMIT=30.000000
         - SMOOTH_FRAME_RATE_UPPER_LIMIT=60.000000
         - USE_FIXED_FRAME_RATE=false
         - FIXED_FRAME_RATE=60.000000
         - MIN_DESIRED_FRAME_RATE=30.000000
         - NET_CLIENT_TICKS_PER_SECOND=60
      volumes:
         - ./palworld:/palworld/
```
</details>
