### ISSUE TITLE
Palworld cannot update

### ISSUE THREAD

**Issue by MeCode4Food** [thijsvanloef/palworld-server-docker#609]
## Describe the bug
Restarted server today after client update (v0.3.7.58983)
However, container is not able to update its server version with error logs:

```log
palworld-server  | ****Checking for new Palworld Server updates****
palworld-server  | The server response does not contain the expected BuildID. Unable to check for updates!
```

## OS information (IMPORTANT)

- OS:  Ubuntu
- Palworld Version:  server at  v0.3.6.57672
- Docker Image Version:  latest

## Hardware information (IMPORTANT)

- CPU:  4vCPU
- Memory:  8gb (for 2 players)

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
        # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
      environment:
         PUID: 1000
         PGID: 1000
         PORT: 8211 # Optional but recommended
         PLAYERS: 16 # Optional but recommended
         SERVER_PASSWORD: "..." # Optional but recommended
         MULTITHREADING: true
         RCON_ENABLED: true
         RCON_PORT: 25575
         TZ: "UTC"
         ADMIN_PASSWORD: "..."
         COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         SERVER_NAME: "..."
         SERVER_DESCRIPTION: "..."
         ALLOW_CONNECT_PLATFORM: "Steam" # Defaults to "Steam" if not set, set this to "Xbox" if you want to host a server for Xbox players. CROSSPLAY BETWEEN XBOX-STEAM IS NOT YET SUPPORTED
      volumes:
         - ./palworld:/palworld/

```

</details>
