### ISSUE TITLE
Server Not Installed Properly

### ISSUE THREAD

**Issue by Juice805** [thijsvanloef/palworld-server-docker#637]
## Describe the bug

The server is not installed properly on launch

## To Reproduce

1. Run in Docker Desktop for macOS

## Expected behavior

Server running

## Actual behavior

Server does not run

## OS information (IMPORTANT)

- OS:  macOS 15.1.1
- Palworld Version:  UNKNOWN (Doesn't install)
- Docker Image Version:  1.0.0 & `dev` @ 4a1f191

## Hardware information (IMPORTANT)

- CPU: M1
- Memory:  16GB

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
services:
  palworld:
    image: ghcr.io/thijsvanloef/palworld-server-docker:dev
    restart: unless-stopped
    stop_grace_period: 60s # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
      # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
    env_file: "~/Cloud/iCloud/Projects/DockerCompose/palworld.env"
    volumes:
      - "~/Server/palworld/:/palworld/"
```

```
PUID=1000
PGID=1000
PORT=8211 # Optional but recommended
PLAYERS=16 # Optional but recommended
SERVER_PASSWORD="X" # Optional but recommended
MULTITHREADING=true
RCON_ENABLED=true
RCON_PORT=25575
TZ="America/Los_Angeles"
ADMIN_PASSWORD="X"
COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
SERVER_NAME="X"
SERVER_DESCRIPTION="Palworld server for X & friends"
ALLOW_CONNECT_PLATFORM="Steam" # Defaults to "Steam" if not set, set this to "Xbox" if you want to host a server for Xbox players. CROSSPLAY BETWEEN XBOX-STEAM IS NOT YET SUPPORTED
```
</details>

## Container/Host Logs (IMPORTANT)

<details><summary>Logs</summary>

```log
****EXECUTING USERMOD****
usermod: no changes
Server installation not detected.
****Starting Installation****
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1733269577
-- type 'quit' to exit --
Loading Steam API...IPC function call IClientUtils::GetSteamRealm took too long: 555 msec
Fatal error: futex robust_list not initialized by pthreads
src/common/framefunction.cpp (238) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[Bootstrapper HTTP Client] still registered
cp: cannot stat './PalServer.sh': No such file or directory
sed: can't read ./PalServer-arm64.sh: No such file or directory
chmod: cannot access './PalServer-arm64.sh': No such file or directory
./PalServer-arm64.sh does not exist.
Server Not Installed Properly
```

</details>

## Additional context

Tried deleting the only bound directory to reset, but luck

## Bug Report Checklist

- [x] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [x] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have included all relevant information required above.
- [ ] I am willing to fix this bug
