### ISSUE TITLE
Steam Guard Tests

### ISSUE THREAD

**Issue by T0biii** [thijsvanloef/palworld-server-docker#651]
Some Tests with Steam Guard.
With this setup (use depot downloader) Steam Guard may work

Got a Info in the Steam app to confirm 2fa.

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for >
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
        # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
      environment:
         TARGET_MANIFEST_ID: "4278745071359475598"
         STEAM_USERNAME: "steam-username"
         STEAM_PASSWORD: "steam-password"
         USE_DEPOT_DOWNLOADER: true
      volumes:
         - ./palworld:/palworld/
```

```cmd
palworld-server  | ****EXECUTING USERMOD****
palworld-server  | usermod: no changes
palworld-server  | Server installation not detected.
palworld-server  | ****Starting Installation****
palworld-server  | Installing Target Version: 4278745071359475598
palworld-server  | Downloading server files using DepotDownloader
palworld-server  | Sending Discord json: {"embeds":[{"title":"Install","description":"Server is updating...","color":15258703}],"flags":0}
palworld-server  | curl: (22) The requested URL returned error: 405
palworld-server  | Connecting to Steam3... Done!
palworld-server  | Logging 'steam-username' into Steam3...
palworld-server  | STEAM GUARD! Use the Steam Mobile App to confirm your sign in...
palworld-server  |  Done!
palworld-server  | Using Steam3 suggested CellID: 91
palworld-server  | Got 292 licenses for account!
palworld-server  | Got AppInfo for 2394010
palworld-server  | Using app branch: 'public'.
palworld-server  | Got depot key for 2394012 result: OK
palworld-server  | Processing depot 2394012
palworld-server  | Downloading depot manifest... Got manifest request code for 2394012 4278745071359475598 result: 6415651911523267910
palworld-server  |  Done!
palworld-server  | Manifest 4278745071359475598 (06/25/2024 14:52:07)
palworld-server  | Downloading depot 2394012
```

But i tested too much for now so that i get a `Unable to login to Steam3: RateLimitExceeded`

Just some infos no real issue here :)
