### ISSUE TITLE
Config Resetting

### ISSUE THREAD

**Issue by Ronambulo** [thijsvanloef/palworld-server-docker#665]
## Describe the bug

Im trying to change the hatch egg time but the env is not working and i dont know why it keeps reseting to 72

## To Reproduce

1. Go to the .yaml file and chanhge the variable
2. start the server

## Expected behavior

eggs hatching faster

## Actual behavior

eggs hatching in default speed

## Screenshots

![Image](https://github.com/user-attachments/assets/180c5fbd-31bd-43f4-8488-9fe23841f87f)
in theory it is using the env variables

![Image](https://github.com/user-attachments/assets/b313b081-fb02-4885-be1a-20d91ff888c0)
thats my 'palworld-server/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini'

## OS information (IMPORTANT)

- OS:  CasaOS in Debian
- Palworld Version:  Latest
- Docker Image Version:  Latest

## Hardware information (IMPORTANT)

- CPU:  
- Memory:  

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
name: palworld-server
services:
    palworld-server:
        cpu_shares: 90
        command: []
        container_name: palworld-server-test
        deploy:
            resources:
                limits:
                    memory: "33568063488"
                reservations:
                    memory: "4294967296"
        environment:
            ADMIN_PASSWORD: E26r10dr04jp
            COMMUNITY: "false"
            MULTITHREADING: "true"
            PGID: "1000"
            PLAYERS: "12"
            PORT: "8211"
            PUID: "1000"
            RCON_ENABLED: "true"
            RCON_PORT: "25575"
            SERVER_NAME: "Wachinga"
            SERVER_PASSWORD: "AWSEDRFTGY"
            TZ: Europe/Madrid
            PAL_EGG_DEFAULT_HATCHING_TIME: 1.000000
        hostname: palworld-server
        image: thijsvanloef/palworld-server-docker:latest
        labels:
            icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/palworld-server/icon.png
        network_mode: bridge
        ports:
            - mode: ingress
              target: 8211
              published: "8211"
              protocol: udp
            - mode: ingress
              target: 27015
              protocol: udp
            - mode: ingress
              target: 25575
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/palworld-server
              target: /palworld
              bind:
                create_host_path: true
networks:
    default:
        name: palworld-server_default
x-casaos:
    architectures:
        - amd64
        - arm64
    author: Cp0204
    category: Games
    description:
        en_us: Get started with hosting your own Palworld Dedicated Server. Palworld is an action-adventure, survival, and monster-taming game created and published by Japanese developer Pocket Pair. The game is set in an open world populated with animal-like creatures called "Pals", which players can battle and capture to use for base building, traversal, and combat.
        zh_cn: 创建你自己的《幻兽帕鲁》专用服务器。《幻兽帕鲁》是由日本开发商Pocket Pair推出的一款动作冒险生存游戏。游戏设定在一个居住着类似动物的生物“帕鲁”的开放世界中，玩家可以战斗并捕捉帕鲁，然后用它们来建造基地、骑乘和战斗。《幻兽帕鲁》可单人游玩，也可通过私人多人服务器来让最多4名玩家同时在线游戏，还支持最多32名玩家在一个服务器上进行网络游戏。
    developer: thijsvanloef
    hostname: ""
    icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/palworld-server/icon.png
    index: /
    is_uncontrolled: false
    main: palworld-server
    port_map: ""
    scheme: http
    screenshot_link:
        - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/palworld-server/screenshot-1.png
        - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/palworld-server/screenshot-2.png
        - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/palworld-server/screenshot-3.png
    store_app_id: palworld-server
    tagline:
        en_us: Easily run a Palworld Dedicated Server
        zh_cn: 轻松运行《Palworld 幻兽帕鲁》专用服务器
    thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/palworld-server/thumbnail.png
    tips:
        before_install:
            en_us: |
                This application is a game private service with high performance requirements:

                | Resources | Minimum | Recommended |
                | ---- | ---- | ---- |
                | CPU | 4 core | 4+ core |
                | RAM | 16GB | 32GB+ |
                | Storage | 8GB | 20GB |

                > Has been tested 1 player logged in to play 2GB RAM usage.

                Environment variables that should be modified after installation:

                | Variables | Information | Defaults |
                | ---- | ---- | ------ |
                | SERVER_NAME | Server Name | `World of Pals` |
                | SERVER_PASSWORD | Server Password | `worldofpals` |
                | ADMIN_PASSWORD | Server administrator password | `adminPasswordHere` |

                Other parameters of the game server can be set in the environment variables, please read the [documentation](https://github.com/thijsvanloef/palworld-server-docker?tab=readme-ov-file#editing-server-settings).
            zh_cn: |
                本应用属于游戏私服，性能要求较高：

                | 资源 | 最小 | 推荐 |
                | ---- | ---- | ---- |
                | CPU  | 4核| 4核+ |
                | 运存   | 16GB | 32GB+ |
                | 存储空间 | 8GB | 20GB |

                > 经测试单人登入游玩约 2GB RAM 占用。

                安装后应修改的环境变量：

                | 变量 | 信息 | 默认值 |
                | ---- | ---- | ------ |
                | `SERVER_NAME` | 服务器名称  | `World of Pals` |
                | `SERVER_PASSWORD` | 服务器密码 | `worldofpals` |
                | `ADMIN_PASSWORD` | 服务器管理员密码 | `adminPasswordHere` |

                在环境变量中还可以设置游戏服务器其他参数，请阅读[文档](https://github.com/thijsvanloef/palworld-server-docker/blob/main/docs/zh-CN/README.md#编辑服务器配置)。
    title:
        custom: ""
        en_us: Palworld Dedicated Server
        zh_cn: 《幻兽帕鲁》私服
```

</details>

## Container/Host Logs (IMPORTANT)

<details><summary>Logs</summary>

```log
<!-- Insert logs here -->
```

</details>

## Additional context

![Image](https://github.com/user-attachments/assets/85034d89-a7b9-4202-b162-6b1b6d1ac802)
yes, i tried taking in and out the egg. The problem is in the .ini file or .yaml i think

## Bug Report Checklist

- [*] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [*] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [*] I have included all relevant information required above.
- [ ] I am willing to fix this bug
