### ISSUE TITLE
BASE_CAMP_WORKER_MAX_NUM doesn't work.

### ISSUE THREAD

**Issue by fashenrique** [thijsvanloef/palworld-server-docker#668]
## Describe the bug

BASE_CAMP_WORKER_MAX_NUM doesn't work.

## To Reproduce

1. Go to docker-compose.yml;
2. Add the line BASE_CAMP_WORKER_MAX_NUM=20;
3. Restart docker;
4. Level Max from the base, but the max worker still in 15;

## Expected behavior

Update the base for 20 worker on max level

## Actual behavior

they still on level 15

## Screenshots

![Image](https://github.com/user-attachments/assets/bb6b7f96-d118-4887-8cb4-a7c333f2cbfe)

## OS information (IMPORTANT)

- OS:   Ubuntu 24.04.1 LTS
- Palworld Version:  Win C v0.4.14.65422(EA15....)
- Docker Image Version:  Docker version 27.4.1, build b9d17ea

## Hardware information (IMPORTANT)

- CPU:  quad core intel
- Memory:   8GB ddr5

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
 services:
    palworld:
       image: thijsvanloef/palworld-server-docker:latest
       restart: unless-stopped
       container_name: palworld-server
       ports:
         - 8211:8211/udp
         - 27015:27015/udp
       environment:
          - PUID=1000
          - PGID=1000
          - PORT=8211
          - PLAYERS=8 # Número de vagas do servidor
          - MULTITHREADING=true
          - RCON_ENABLED=true
          - RCON_PORT=25575
          - TZ=UTC-3
          - COMMUNITY=false  # Mostra o seu servidor na listagem da comunidade.
          - EXP_RATE=20
          - PAL_CAPTURE_RATE=2
          - PAL_SPAWN_NUM_RATE=2
          - COLLECTION_DROP_RATE=5
          - COLLECTION_OBJECT_RESPAWN_SPEED_RATE=1
          - ENEMY_DROP_ITEM_RATE=5
          - DROP_ITEM_MAX_NUM=5000
          - BASE_CAMP_MAX_NUM_IN_GUILD=10
          - BASE_CAMP_WORKER_MAX_NUM=20
          - ENABLE_INVADER_ENEMY=True # Ligar/desligar invasões
          - PAL_EGG_DEFAULT_HATCHING_TIME=0 # Tempo em horas para incubar os ovos.
       volumes:
          - ./servidor:/palworld/

```

</details>

## Bug Report Checklist

- [x] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [x] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [x] have included all relevant information required above.
- [ ] I am willing to fix this bug
