### ISSUE TITLE
Global Pal Box will not work on server

### ISSUE THREAD

**Issue by Hockilliona1re** [thijsvanloef/palworld-server-docker#687]
## Describe the bug

Hi Guys,

i have spend the last half day trying to enable the Global Pal Box importing and exporting on the server. I am unable to... i have added the Variables to the environment in the YAML Configuration (ie. ALLOW_GLOBAL_PALBOX_EXPORT: True ALLOW_GLOBAL_PALBOX_IMPORT: true) with zero luck. In game, when attempting to use the Global Pal Box, it says that Pal Reconstruction Failed and isn not enabled on the server in the world settings. I have checked the PalWorldSettings.ini and unless i choose to also add the 'environment variable' DISABLE_GENERATE_SETTINGS: true then it auto deletes the settings. with the DISABLE_GENERATE_SETTINGS set to true it keeps the .ini file with global settings set but still does not reflect this in game. I am able to change other parameters in the .ini such as EXP_RATE. I just cannot for the life of me get the Global Pal Box Import and Export in the game to work. Any help would be much appreciated.

## Screenshots

![Image](https://github.com/user-attachments/assets/7f66dafe-e24f-4cb5-8c39-6c659a6434cc)

## OS information (IMPORTANT)

- OS:  <Synology DSM 7.2.1-69057>
- Palworld Version:  <0.5.1.68353>
- Docker Image Version:  <palworld-server-docker:latest>

## Hardware information (IMPORTANT)

- CPU:  <DS920+>
- Memory:  <20gb>

## docker-compose.yml contents (IMPORTANT)

![Image](https://github.com/user-attachments/assets/25f49739-ab1a-4cfa-a976-ac4e78a60d29)

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: no
      container_name: palworld-server
      stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
        # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
      environment:
         PUID: 1026
         PGID: 100
         PORT: 8211 # Optional but recommended
         PLAYERS: 16 # Optional but recommended
         SERVER_PASSWORD: # Optional but recommended
         MULTITHREADING: true
         RCON_ENABLED: true
         RCON_PORT: 25575
         TZ: "Australia/Sydney"
         ADMIN_PASSWORD: "palworld94"
         COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         SERVER_NAME: "Imagination Land"
         SERVER_DESCRIPTION: "Imaaaaaggggiiinnnnnnaaaaaaaaaaaaaation"
         ALLOW_CONNECT_PLATFORM: "Steam" # Defaults to "Steam" if not set, set this to "Xbox" if you want to host a server for Xbox players. CROSSPLAY BETWEEN XBOX-STEAM IS NOT YET SUPPORTED
         EXP_RATE: 20.000000
         ALLOW_GLOBAL_PALBOX_IMPORT: true
         ALLOW_GLOBAL_PALBOX_EXPORT: true
         DISABLE_GENERATE_SETTINGS: true
      volumes:
         - ./data:/palworld/
```

</details>

## Container/Host Logs (IMPORTANT)

[palworld-server.txt](https://github.com/user-attachments/files/19530295/palworld-server.txt)

```

</details>

## Additional context

<!-- Add any other context about the problem here. -->

## Bug Report Checklist

- [ ] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [ ] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have included all relevant information required above.
- [ ] I am willing to fix this bug
