### ISSUE TITLE
Fast Travel Failing, Assign More Memory

### ISSUE THREAD

**Issue by RhanCandia** [thijsvanloef/palworld-server-docker#707]
## Describe the bug

Fast travel has really slow loading screens and more often fails and just drops me back to the base.
Another thing I noticed is it won't use more memory on my server. It just usually hovers around 4GB of RAM. 

## To Reproduce

1. Fast travel to a distant area
2. Loading screen takes too long and eventually drops you back to the base

## Expected behavior

Be teleported to the distance area chosen.

## Actual behavior

Long loading screen time and gets dropped back to the base, not the desired location.

## OS information (IMPORTANT)

- OS: Ubuntu on Oracle ARM64
- Palworld Version: Latest
- Docker Image Version: Latest

## Hardware information (IMPORTANT)

- CPU: ARM64 4vCPU
- Memory:  24GB
## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
---
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
      # - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211  # Optional but recommended
      PLAYERS: 6  # Optional but recommended
      SERVER_PASSWORD: "REDACTED"  # Optional but recommended
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      TZ: "UTC"
      ADMIN_PASSWORD: "REDACTED"
      COMMUNITY: false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "REDACTED"
      SERVER_DESCRIPTION: "REDACTED"
      CROSSPLAY_PLATFORMS: "Steam"
      AUTO_PAUSE_ENABLED: true
    volumes:
      - REDACTED
```

</details>

## Bug Report Checklist

- [ x] I searched for my issue on the [Known issues page](https://palworld-server-docker.loef.dev/known-issues)
- [x ] I searched for my issue in the [Closed issues](https://github.com/thijsvanloef/palworld-server-docker/issues?q=is%3Aissue+is%3Aclosed)
- [ x] I have included all relevant information required above.
- [ x] I am willing to fix this bug
