### ISSUE TITLE
Rcon-cli ShowPlayers doesn't return anything

### ISSUE THREAD

**Issue by frey-er** [thijsvanloef/palworld-server-docker#97]
## Describe the bug

when running : 
docker exec -it palworld-server rcon-cli "ShowPlayers"

Of course the docker name is correct because i can run other cmd

## To Reproduce
docker exec -it palworld-server rcon-cli "ShowPlayers"

## Expected behavior

Returning the list of player

## Desktop (please complete the following information)
From the terminal of the ubuntu 22.04 running docker

## docker-compose.yml contents

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      ports:
        - 8211:8211/udp
        - 27011:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=2 # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - ADMIN_PASSWORD=""
         - COMMUNITY=false
         - SERVER_PASSWORD=""
         - SERVER_NAME=""
         - PUBLIC_PORT=8211
         - UPDATE_ON_BOOT=true
      labels:
         - "com.centurylinklabs.watchtower.enable=true"
      volumes:
         - palworld_server_test:/palworld/
volumes:
  palworld_server_test:  # Volume definition
    driver: local
```
